### ISSUE TITLE
Please publish git tags for releases to GitHub

### ISSUE THREAD

**Issue by shepmaster** [hermitcore/rusty-hermit#1]
Only 0.1.1 is present, but 0.1.5 is on crates.io

**Comment by stlankes** [comment]
You are right, I will do it

**Comment by shepmaster** [comment]
You closed this issue, but there's [still only 0.1.1](https://github.com/hermitcore/rusty-hermit/releases).

**Comment by stlankes** [comment]
You were too fast for me. I add the latest versions. I am currently working on the other versions.

**Comment by stlankes** [comment]
I have tagged every version, which I was able to reconstruct. In the future I will maintain the tags better.
