### ISSUE TITLE
diverging state of master and devel branches

### ISSUE THREAD

**Issue by jschwe** [hermitcore/rusty-hermit#10]
I am somewhat confused why master and devel branch have diverged so much. As someone new to the codebase I can't even be sure to what exactly the differences are. 

From what I've seen the master branch takes hermit-sys from crates.io, and this makes it hard to keep devel and master in sync. What are the benefits in downloading hermit-sys from crates.io versus using hermit-sys with the lib-hermit submodule at a fixed commit?

**Comment by stlankes** [comment]
Hm, it is confusing. For external user is the crate.io version easier to use. They have not to add libhermit as submodule. In addition, if they use libhermit as submodule, they are not able to publish an application at crates.io.

**Comment by jschwe** [comment]
I think it might be better to point an external user to a specific repository that provides a demo app using crates.io. That's basically what https://github.com/hermitcore/rusty-demo/ was meant for, wasn't it?
Regarding your second point, isn't [Multiple locations for dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations) a solution for that problem?

**Comment by stlankes** [comment]
Today, the branch `devel` isn't longer used. See #28
