### ISSUE TITLE
fail to build demo example in latest nightly 

### ISSUE THREAD

**Issue by maxtnuk** [hermitcore/rusty-hermit#108]
when i build demo with latest nightly rust, i got build fail like this 
```
Caused by:
  process didn't exit successfully: `/home/maxtnt/workspace/uni_kernel_test/target/debug/build/hermit-sys-13f6625d237250fc/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=HERMIT_IP
  cargo:rerun-if-env-changed=HERMIT_GATEWAY
  cargo:rerun-if-env-changed=HERMIT_MASK
  Build libhermit-rs output-status: exit code: 101
  Build libhermit-rs output-stdout: 
  Build libhermit-rs output-stderr:     Updating crates.io index
      Blocking waiting for file lock on package cache
  error: Package `test v0.0.0 (/home/maxtnt/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have the feature `compiler-builtins-asm`
```
it looks like problem with **compiler-builtins-asm** feature in test mod \
I found that **compiler-builtins-asm** feature is removed in nightly-2021-01-22(1.51.0) \
check out this [commit](https://github.com/rust-lang/rust/commit/6275a29dbe153b48f9d0a38dbc9a5facd1d3c307#diff-fd136b0ffa6ed23dcb1c7c8ce4cf410c2b312827c8602fe3d523ecf044be1d90) \
when i downgrade the nightly version, it works!!

so i think we need specify nightly version in toolchain or modify source code

**Comment by stlankes** [comment]
Thanks for the hint. I knew that they wanted to change the default behavior. I was not aware that this has already happened. I will fix it.

**Comment by stlankes** [comment]
I think that #110 solves this issue.

**Comment by maxtnuk** [comment]
Thanks!!
