### ISSUE TITLE
after new release 0.1.20 the build seems broken. The docs doesn't the reflect the changes.

### ISSUE THREAD

**Issue by alessio-proietti** [hermitcore/rusty-hermit#123]
Hi,

after new commits I'm not able anymore to build a project with hermit-sys as dependency, it seems related to a change in the build toolchain and config.

Here the log:

> error: failed to run custom build command for `hermit-sys v0.1.20`
> 
> Caused by:
>   process didn't exit successfully: `/home/aproietti/hello_world/target/debug/build/hermit-sys-d0bdb23e975a1f94/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=HERMIT_IP
>   cargo:rerun-if-env-changed=HERMIT_GATEWAY
>   cargo:rerun-if-env-changed=HERMIT_MASK
>   Build libhermit-rs output-status: exit status: 101
>   Build libhermit-rs output-stdout: 
>   Build libhermit-rs output-stderr:     Updating crates.io index
>      Compiling compiler_builtins v0.1.39
>      Compiling core v0.0.0 (/home/aproietti/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
>      Compiling autocfg v1.0.1
>   error: Error loading target specification: Could not find specification for target "x86_64-unknown-hermit-kernel". Run `rustc --print target-list` for a list of built-in targets
> 
>   error: could not compile `core`
> 
>   To learn more, run the command again with --verbose.
>   warning: build failed, waiting for other jobs to finish...
>   error: build failed
> 
> 
>   --- stderr
>   thread 'main' panicked at 'assertion failed: output.status.success()', /home/aproietti/.cargo/registry/src/github.com-1ecc6299db9ec823/hermit-sys-0.1.20/build.rs:107:5
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by stlankes** [comment]
Yes, I notice this issue. The latest version should fix. Does it work on you systems?

**Comment by alessio-proietti** [comment]
The fact is I have to use the exact toolchain nightly indicated in a file here in the repo and not the latest... so it builds now but I sort of reverse engineered the build

**Comment by stlankes** [comment]
Every day to switch the toolchain is difficult. Do you get with the current night some errors like "unknown token in expression"?

**Comment by stlankes** [comment]
hermitcore/libhermit-rs#192 should fix this issue.
