### ISSUE TITLE
Clean up Branches and developement workflow

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/rusty-hermit#13]
Just as proposed in https://github.com/hermitcore/libhermit-rs/issues/46 . This is the twin issue for rusty-hermit

**Comment by stlankes** [comment]
Do you like my cleanups?

**Comment by jounathaen** [comment]
Of course I do :heart: :wink: 
But I'd keep this issue open, until the master branch and devel branch are in a sane relationship

**Comment by jounathaen** [comment]
Related: #10

**Comment by jounathaen** [comment]
What's the status? The devel branch still converges by ~150 Commits but all recent pull requests go to the master branch. Can the devel branch be deleted?
