### ISSUE TITLE
Network broke with toolchain upgrade 

### ISSUE THREAD

**Issue by mkroening** [hermitcore/rusty-hermit#158]
https://github.com/hermitcore/rusty-hermit/commit/f66737362dd9217220dc95d3e49e906472e6ce54 broke networking.

`nightly-2021-07-01` works, but when building that one locally, it does not anymore. What am I doing wrong? :thinking:

**Comment by stlankes** [comment]
Fun fact, https://rusty-hermit.k8s.eonerc.rwth-aachen.de still works and is up-to-date (https://git.rwth-aachen.de/acs/public/hermitcore/rusty-hermit/-/pipelines).

**Comment by stlankes** [comment]
Ah, I forgot that this version use RTL8132 as network interface.

**Comment by mkroening** [comment]
The specific commit introducing the problem is an update to cargo: https://github.com/rust-lang/rust/commit/f4981b4aedac1d9f750dc28bd7524b3ac4bb9b25

**Comment by mkroening** [comment]
The specific PR causing this change in behavior is https://github.com/rust-lang/cargo/pull/9601.
