### ISSUE TITLE
RWTH OS Link: Expired Certificate

### ISSUE THREAD

**Issue by splitcells** [hermitcore/rusty-hermit#174]
https://github.com/hermitcore/rusty-hermit -> https://hermitcore.org/ -> Research Project -> http://www.os.rwth-aachen.de/

**Comment by stlankes** [comment]
I fixed the link. I have to update the web site. It isn't up-to-date...

**Comment by mkroening** [comment]
https://github.com/hermitcore-org/homepage/commit/4aa0aaa1b9913e9b71630395a2fda531fe39be8c changed the link to http://os.rwth-aachen.de but it still gives me the same error message:

```
Websites prove their identity via certificates, which are valid for a set time period. The certificate for os.rwth-aachen.de expired on 11/4/2020.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by jounathaen** [comment]
@splitcells Thank's for reporting :-)
