### ISSUE TITLE
Request for major version number change

### ISSUE THREAD

**Issue by kastonework** [hermitcore/rusty-hermit#189]
Hello -

hermit-abi is pulled into our project via an indirect dependency (therefore we are unable to specify an older version of hermit-abi).

Since the update to 0.1.20, our project will no longer build; we get the following error: 
  ```Downloaded hermit-abi v0.1.20
error: failed to parse manifest at `/home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/hermit-abi-0.1.20/Cargo.toml`
Caused by:
  feature `edition2021` is required
  ```
Our project is using edition2018 and our build system is on an older rustc version. 

Could you update the Major version number so that the prior edition2018 version is pulled?

**Comment by kastonework** [comment]
Closing this until I determine if the proper solution is just that we need to update rustc in our build environments.

**Comment by stlankes** [comment]
It was a mistake from our side. I yank this version and create a version, where I increase the major version number.
