### ISSUE TITLE
Rework README

### ISSUE THREAD

**Issue by mkroening** [hermitcore/rusty-hermit#196]
The README is partly outdated and can be streamlined.

**Comment by stlankes** [comment]
Do I fix it with #330 ?

**Comment by mkroening** [comment]
I think the problem was mostly solved by https://github.com/hermitcore/rusty-hermit/pull/301. But let's talk about the README together before closing this issue.

**Comment by mkroening** [comment]
A lot of this was done in https://github.com/hermitcore/rusty-hermit/pull/380.
