### ISSUE TITLE
Function read in std::net::TcpStream doesn't block

### ISSUE THREAD

**Issue by philipp-fensch** [hermitcore/rusty-hermit#205]
calling set_nonblocking(false) on the stream returns Error with message "unable to set blocking mode".

**Comment by philipp-fensch** [comment]
Minimal Example, that should work in Rusty-Hermit:

Server: (Squares numbers received and sends them back)
https://github.com/philipp-fensch/tcp-server

Client:
Without Rusty-Hermit: https://github.com/philipp-fensch/tcp-client
With Rusty-Hermit: https://github.com/philipp-fensch/rusty-hermit/tree/tcp-stream

**Comment by mkroening** [comment]
I identified the issue and drafted a PR (https://github.com/hermitcore/rusty-hermit/pull/208).
