### ISSUE TITLE
Ensure that rusty-hermit runs on uhyve

### ISSUE THREAD

**Issue by jschwe** [hermitcore/rusty-hermit#3]
rusty-hermit currently does not work using uhyve (on Ubuntu bionic at least). I'm opening this issue so that I can link to all related issues and PRs in one place. 

- [x] [Ensure processor frequency can be read](https://github.com/hermitcore/libhermit-rs/issues/30)
- [ ] [Fix panic due to uninitialized environment](https://github.com/hermitcore/rust/pull/1)
- [x] [Add CI tests for rusty-hermit running on uhyve ](https://github.com/hermitcore/rusty-hermit/issues/2)

**Comment by stlankes** [comment]
Funny, I use always Ubuntu to test it. In addition, also our CI based on Ubuntu 18.04.

**Comment by jschwe** [comment]
As far as I'm aware all CI tests currently use Qemu. Qemu + rusty-hermit works fine for me too, I'm just having problems with uhyve + rusty-hermit. I've verified that the same issues appear in freshly configured virtual machines (in vagrant boxes on my local machine and in the Travis CI environment), so I'm fairly confident it's not just some local issue.

**Comment by stlankes** [comment]
I updated you first issue list and convert it to a todo list.

**Comment by jschwe** [comment]
Point 1 and 3 have been resolved. 
I haven't encountered Point 2 in a long time either, so that issue seems to have resolved itself. I'm still able to reproduce the issue when building with the nightly version I used at the time, but since this is apperently not an issue anymore I'm closing this issue.
