### ISSUE TITLE
File location improvements

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/rusty-hermit#35]
As suggested in https://github.com/hermitcore/libhermit-rs/pull/60:
I'd think that the following names/locations would be easier to comprehend:
-    img -> assets/images
-    demo and netbench -> util/demo util/netbench

**Comment by stlankes** [comment]
Why do you want to create an util directory?

**Comment by jounathaen** [comment]
To structure the repository better? :stuck_out_tongue_winking_eye:

**Comment by stlankes** [comment]
Cann I close this issue?
