### ISSUE TITLE
Publish doc to github page

### ISSUE THREAD

**Issue by lzutao** [hermitcore/rusty-hermit#41]
Since docs.rs has no build for hermit, and with
https://github.com/hermitcore/rusty-hermit/blob/667195d509afd8ea5a4c25ac94e52fe353b49414/hermit-abi/Cargo.toml#L28
We only build doc for `x86_64-unknown-hermit`. The latest doc for hermit-abi is https://docs.rs/hermit-abi/0.1.8/hermit_abi/ , where the crates.io version is 0.1.14.
I suggest using CI service to generate doc and publish it to github pages.

**Comment by stlankes** [comment]
You are right. We will change it.

**Comment by stlankes** [comment]
Now, we published the documentation at GitHub pages and add a link in the readme.

**Comment by lzutao** [comment]
https://hermitcore.github.io/rusty-hermit/ is 404

**Comment by stlankes** [comment]
Yes, I have to set a redirection to https://hermitcore.github.io/rusty-hermit/hermit_abi/

**Comment by stlankes** [comment]
Now, it should work.

**Comment by lzutao** [comment]
Great!
