### ISSUE TITLE
Use `#[non_exhaustive]` when applicable

### ISSUE THREAD

**Issue by lzutao** [hermitcore/rusty-hermit#42]
https://github.com/hermitcore/rusty-hermit/blob/ad0e4d2966ded18fd7f56c0c45403ba02eb069f3/hermit-abi/src/lib.rs#L128-L129
https://github.com/hermitcore/rusty-hermit/blob/ad0e4d2966ded18fd7f56c0c45403ba02eb069f3/hermit-abi/src/lib.rs#L150-L151

**Comment by stlankes** [comment]
I remove it. Thanks for the hint.
