### ISSUE TITLE
Defined location for examples and benchmarks

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/rusty-hermit#51]
Now we have a separation between [Rusty Demo](https://github.com/hermitcore/rusty-demo) and the [demo in this repository](https://github.com/hermitcore/rusty-hermit/tree/master/demo).

**Comment by jounathaen** [comment]
This also applies to [httpd](https://github.com/hermitcore/rusty-hermit/tree/master/httpd) and [netbench](https://github.com/hermitcore/rusty-hermit/tree/master/netbench).

I'd say, we either
- put ALL RustyHermit examples/demos in an `example` folder and a `benches` folder followin the [Cargo package layout](https://doc.rust-lang.org/cargo/guide/project-layout.html).  This would imply that the examples and benches have to work with the default cargo commands

- create an extra repository containing these kind of stuff

**Comment by stlankes** [comment]
Problem is solved by PR #59
