### ISSUE TITLE
rust-toolchain file and README

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/rusty-hermit#56]
The `rust-toolchain` file introduced in https://github.com/hermitcore/rusty-hermit/pull/54 is a better way than setting the default globally.

But this needs to be reflected in the README

**Comment by garrettgu10** [comment]
Now that there is a rust-toolchain file, this means that the build process is the same as before, only that setting "rustup default" is now optional, right?

**Comment by stlankes** [comment]
Yes
