### ISSUE TITLE
What is the expected way to get randomness on hermitcore?

### ISSUE THREAD

**Issue by josephlr** [hermitcore/rusty-hermit#63]
I'm one of the maintainers for [`getrandom`](https://docs.rs/getrandom), a `no_std` library which attempts to define the "standard" way to get cryptographic entropy on every Rust target. The `rand` crate and others use this crate under the hood.

As far as I can tell HermitCore doesn't expose or have a way to get OS-based randomness. For that reason, we don't currently support Hermit.

Are users simply expected to call RDRAND? This is reasonable, provided that HermitCore is `x86_64` only.

**Comment by stlankes** [comment]
You find at https://github.com/hermitcore/libhermit-rs/blob/master/src/syscalls/random.rs#L20-L31 our generator of random numbers. If RDRAND is available, it will use RDRAND. Otherwise, you het only pseudo random number. But you are right, I should add a function in `hermit-abi`.

**Comment by josephlr** [comment]
Sounds good, we will just call RDRAND directly in getrandom (we already have the implementation). Also, the fallback Hermit RNG mechanism is not cryptographicly secure, is that a problem?

**Comment by jbreitbart** [comment]
I am afraid directly calling RDRAND will not work well for the upcoming releases, as there is same work for AARCH64 see e.g. #61 Do we have a plan on how to do that on arm @stlankes? And yes, the fallback isn't great, we should be sure that this is at least clearly exposed to the users...

**Comment by stlankes** [comment]
> Sounds good, we will just call RDRAND directly in getrandom (we already have the implementation). Also, the fallback Hermit RNG mechanism is not cryptographicly secure, is that a problem?

We use also RDRAND to generate random numbers. However, our fallback on systems without RDRAND support is currently not cryptographicly secure.

> Do we have a plan on how to do that on arm @stlankes? 

AARCH64 has also hardware support for random numbers. For instance [RDNR](https://developer.arm.com/docs/ddi0595/h/aarch64-system-registers/rndr) could be solution. I will look in the specification.

**Comment by jbreitbart** [comment]
@josephlr can you a look at https://github.com/hermitcore/libhermit-rs/pull/98 Is calling the syscall fine for you?

**Comment by josephlr** [comment]
> @josephlr can you a look at [hermitcore/libhermit-rs#98](https://github.com/hermitcore/libhermit-rs/pull/98) Is calling the syscall fine for you?

One issue there is the fallback, `getradom`'s API is "fail if you can't get good RNG", so with the current implin libhermit, we would have to use [our RDRAND implementation](https://github.com/rust-random/getrandom/blob/master/src/rdrand.rs#L29-L46) instead of calling the syscall.

> AARCH64 has also hardware support for random numbers. For instance [RDNR](https://developer.arm.com/docs/ddi0595/h/aarch64-system-registers/rndr) could be solution. I will look in the specification.

We looked into this beifly for `getrandom`, one issue we found is that ARM chips (prior to RDNR being common) all have a different way to get cryptographic randomness, so you end up having an explosion of different implementations (depending on what you're targeting).

**Comment by josephlr** [comment]
On thing some OSes do is provide a way to know if the RNG is secure/seeded/whatever. That could work, or have a separate secure_rand() function that won't ever give insecure RNG.

**Comment by stlankes** [comment]
Yeah, this approach is really good. I will add a similar syscall.

**Comment by stlankes** [comment]
I add an interface in #64. Does it meet your requirements?

**Comment by josephlr** [comment]
> I add an interface in #64. Does it meet your requirements?

Yes! That interface looks great (and would allow `getrandom` to work on `aarch64` without needing any additional changes).

**Comment by stlankes** [comment]
I merged #64 and close this issue. Please reopen this issue, if the interface  is not suitable for your use case.
