### ISSUE TITLE
Pipeline is broken with current rust nightly.

### ISSUE THREAD

**Issue by jschwe** [hermitcore/rusty-hermit#7]
I'm currently working on https://github.com/hermitcore/libhermit-rs/pull/40/ and I just can't get the pipeline to work. Compiling (rusty_demo) always fails at the last step with
`error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)`

This error is also present in the gitlab ci pipeline. At first I couldn't reproduce this issue on my machine. 
But after updating my rust nightly I now also run into this issue on my machine. 
`nightly-x86_64-unknown-linux-gnu updated - rustc 1.45.0-nightly (7ced01a73 2020-04-30) (from rustc 1.44.0-nightly (45d050cde 2020-04-21))`

Can anyone else reproduce this?

**Comment by stlankes** [comment]
Yes, I am able to reproduce the problem. I think that we have to disable LTO for the release version. Afterwards it works on my system.

**Comment by jschwe** [comment]
@stlankes Could you also merge this into the devel branch?

Also would you like to keep this issue open, or should we create a new issue for figuring out why LTO doesn't work anymore?

**Comment by stlankes** [comment]
Hm, a new issue will be great.

I will cherry-pick the PR and merge it to devel.

**Comment by jschwe** [comment]
The Pipeline works again since LTO has been disabled for now. Closing this issue. Further discussion of the LTO problem in #15
