### ISSUE TITLE
Preemption is broken

### ISSUE THREAD

**Issue by mwkroening** [hermitcore/rusty-hermit#77]
I can't get APIC timer interrupts working on [uhyve](https://github.com/hermitcore/uhyve).

This is why I was looking how rusty-hermit triggers it, but I was unsuccessful in that as well.

I ran the following program on Linux:
```rust
use std::thread;

fn main() {
    thread::spawn(|| loop {
        println!(" 2")
    });

    loop {
        println!("1 ")
    }
}
```

On my host system, this yields both outputs as expected, but running this in rusty-hermit only prints “1 ”.

Is this expected or is rusty-hermit failing to set up uhyve's APIC timer interrupts as well?

Note that I opened this issue in the parent repository, as I am not sure of the scope of this problem.

**Comment by mwkroening** [comment]
Note that setting `HERMIT_CPUS=2` fixes the symptoms.

**Comment by mwkroening** [comment]
I found that the behavior is identical when running on QEMU. One CPU does not preempt, more than one do.

**Comment by jschwe** [comment]
I don't really have any knowledge about the APIC or the scheduler implementation, but here my two cents on the symptoms:

AFAIK the scheduler in rusty-hermit has some concept of priorities. It seems possible to me that the priority of threads generated via `thread::spawn` is lower than that of the main thread. In that case, the main thread would always be scheduled (if only a single core is available). Linux uses CFS (Completly Fair Scheduler) by default, so the main thread can't starve the spawned thread on Linux. 
You could set a breakpoint / debug print in the scheduler to see if it really is never called.

**Comment by mwkroening** [comment]
Thanks for the fast reply, @jschwe!

Good idea with the priorities! With two cores, the above code also fires the timer handler often, which calls the scheduler, but with one core, it does not. Not firing the interrupt handler is suspicious, but the starving could still be caused by priorities. The timer interrupt seems to operate in one-shot mode and not fire periodically, so if the scheduler would not want to preempt the current thread again in the future because of priorities, this might fit.

Another setup stills seems weird though:

Spawn a second thread, which does not print to `Stdout`:
```rust
use std::thread;

fn main() {
	thread::spawn(|| loop {
		println!(" 2")
	});

	thread::spawn(|| loop {});

	loop {
		println!("1 ")
	}
}
```

Running this code on uhyve with two cores only prints “ 2”, which I interpret as the first thread running on one core and the second thread and the main thread on the other core with the second thread starving the main thread. When printing in the second thread as well, I can read all three outputs again.  So to me, it seems like something is going wrong with the one-shot timer setup when not yielding to the kernel by waiting on `Stdout`'s mutex hidden in `println!` in this case.

I hope this makes some sense.

**Comment by jschwe** [comment]
I don't have any further ideas or time to investigate this currently. Pinging @stlankes since it looks like he might have overlooked this.

**Comment by stlankes** [comment]
RustyHermit uses currently a cooperative scheduler. If you not block a task, the task will never give up the CPU. Your main loop should call `std::thread::yield_now`.

**Comment by mwkroening** [comment]
All right, that makes sense. Thanks for the clarification!
