### ISSUE TITLE
Consider removing git lfs

### ISSUE THREAD

**Issue by jschwe** [hermitcore/rusty-hermit#84]
git LFS is an additional dependancy that needs to be installed. Considering that the gif was removed and the remaining image stored using LFS is only 10 KB in size, we should consider removing LFS. 

On windows using powershell cloning a repo with LFS fails, apparently due to a bug in (windows) openssh.

**Comment by stlankes** [comment]
It is a pain to work with Windows :-)

**Comment by stlankes** [comment]
`libhermit-rs` is maybe a problem. Their is one image, which is 12 MB large.

**Comment by jbreitbart** [comment]
And uhyve uses LFS to store `benches_data/hello_world`

**Comment by jschwe** [comment]
Ah okay, I wasn't aware of that. Removing LFS doesn't make too much sense then.
