### ISSUE TITLE
cmath is missing several functions

### ISSUE THREAD

**Issue by garrettgu10** [hermitcore/rusty-hermit#86]
We found that several math libraries provided by libm were in fact not exposed through the hermit cmath wrapper (sys/cmath.rs), such as pow and log10. This caused linker errors when the compiled program attempted to call these functions.

Consider the following program:
```
#[cfg(target_os = "hermit")]
extern crate hermit_sys;

fn main() {
	println!("{}", 0.42f64.log10());
}
```

**Comment by stlankes** [comment]
Can take a look to PR #87. Does ist help?

**Comment by garrettgu10** [comment]
We were able to add these locally to make things compile. We were actually hoping to contribute a PR that adds all missing cmath functions at once, if that's ok?

**Comment by stlankes** [comment]
Of course! I will accept #87 as first step.

**Comment by stlankes** [comment]
I close this issue because #89 should add all missing symbols.
